name: portfolio
description: My awesome portfolio.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  custom_navigation_bar: ^0.8.2
  json_annotation: ^4.8.1
  url_launcher: ^6.2.2
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.24.2
  flutter_riverpod: ^2.3.6
  go_router: ^8.0.5
  riverpod_annotation: ^2.1.1
  google_fonts: ^4.0.4
  firebase_auth: ^4.2.4
  firebase_crashlytics: ^3.3.0
  firebase_performance: ^0.9.3+8
  firebase_analytics: ^10.7.4
  cloud_firestore: ^4.13.5
  flutter_staggered_grid_view: ^0.7.0
  sliver_tools: ^0.2.12
  text_scroll: ^0.2.0
  carousel_slider: ^4.2.1

  get: ^4.6.6
  get_storage: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  test: ^1.24.9
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/ui/
    - assets/map_style.json
    - assets/icons/menu/
    - assets/icons/tech/
    - assets/icons/png/
    - assets/icons/profile/
    - assets/projects/images/

  fonts:
    - family: MonaSans
      fonts:
        - asset: assets/fonts/mona_sans/MonaSans-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/mona_sans/MonaSans-ExtraLightItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/mona_sans/MonaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/mona_sans/MonaSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/mona_sans/MonaSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/mona_sans/MonaSans-Italic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/mona_sans/MonaSans-Medium.ttf
          weight: 600
        - asset: assets/fonts/mona_sans/MonaSans-MediumItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/mona_sans/MonaSans-SemiBold.ttf
          weight: 800
        - asset: assets/fonts/mona_sans/MonaSans-SemiBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/mona_sans/MonaSans-Bold.ttf
          weight: 900
        - asset: assets/fonts/mona_sans/MonaSans-BoldItalic.ttf
          style: italic
          weight: 900