// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      /*case TargetPlatform.iOS:
        return ios;*/
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyCaqzzmXYrVSSZoOg0p0EH1EsL17oF1l2Q",
      authDomain: "my-portfolio-app-web.firebaseapp.com",
      projectId: "my-portfolio-app-web",
      storageBucket: "my-portfolio-app-web.appspot.com",
      messagingSenderId: "234942646771",
      appId: "1:234942646771:web:6a3d687e8ef2c61ce0aa86",
      measurementId: "G-55R288XXC1"
  );

  /*static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWb0darbmVXwXsZwiaAtp781e8d6Buk7k',
    appId: '1:340847943631:ios:7860341e5dd2cfa448fcba',
    messagingSenderId: '340847943631',
    projectId: 'baptiste-lecat-portfolio',
    storageBucket: 'baptiste-lecat-portfolio.appspot.com',
    iosBundleId: 'com.baptistelecat.portfolioapp',
  );*/
}
